server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:job_hunter}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false